CREATE TABLE pesquisa_educacao_fisica ( 
    codigo INT NOT NULL AUTO_INCREMENT, 
    nome VARCHAR(50) NULL, 
    email VARCHAR(100) NULL, 
    data_nascimento DATE NULL, 
    cpf VARCHAR(14) NULL, 
    aquecimento VARCHAR(1) NULL, 
    beneficio_atividade VARCHAR(1) NULL, 
    esportes_coletivos VARCHAR(1) NULL, 
    frequencia_oms VARCHAR(1) NULL, 
    alimentacao_atividade TEXT NULL, 
    educacao_fisica_escolar TEXT NULL, 
    diferenca_atividade_exercicio TEXT NULL, 
    descanso_recuperacao TEXT NULL, 
    vf_1 VARCHAR(1) NULL, 
    vf_2 VARCHAR(1) NULL, 
    vf_3 VARCHAR(1) NULL, 
    vf_4 VARCHAR(1) NULL, 
    vf_5 VARCHAR(1) NULL, 
    vf_6 VARCHAR(1) NULL, 
    vf_7 VARCHAR(1) NULL, 
    vf_8 VARCHAR(1) NULL, 
    data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (codigo) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;